# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1683ee7204c128a1182df7a81d3cede1b3f8f526bb20c2d1715aa4c225c9ece3cbe031a40effff1b72a2b20945867b1b4bf04069bb8311e14dad2b22ae7e1a1

test:
  secret_key_base: fa2930753594113c20658c0a1993b7853716b4d938bb77c3294092a9f15459749c01ef8d5398cad7d0a75c923a30770380a547233366c46c47e36bc4171b272e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
